/**
 * Env Sync Module
 * Applies environment variable changes to /etc/profile.d/ and tmux
 * Uses diff-based updates for efficiency
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import type { EnvVarDiff } from './env-state-manager.js';

const execAsync = promisify(exec);

/**
 * Apply environment variable changes to /etc/profile.d/ and tmux
 * @param envVars - All environment variables (complete set)
 * @param diff - What changed (add/remove/change)
 */
export async function applyEnvVarChanges(
  envVars: Record<string, string>,
  diff: EnvVarDiff
): Promise<void> {
  console.log(`Applying env var changes: +${Object.keys(diff.toAdd).length} -${diff.toRemove.length} ~${Object.keys(diff.toChange).length}`);

  // Step 1: Update /etc/profile.d/vibe-anywhere-env.sh
  await updateProfileFile(envVars);

  // Step 2: Update tmux environment (using diff for efficiency)
  await updateTmuxEnvironment(diff);

  console.log('Environment variables applied successfully');
}

/**
 * Write all env vars to /etc/profile.d/vibe-anywhere-env.sh
 * Requires sudo permissions (agent has NOPASSWD sudoers)
 */
async function updateProfileFile(
  envVars: Record<string, string>
): Promise<void> {
  const envLines = Object.entries(envVars).map(([key, value]) => {
    // Escape single quotes in value: replace ' with '\''
    const escapedValue = value.replace(/'/g, "'\\''");
    return `export ${key}='${escapedValue}'`;
  });

  const envContent = `# Vibe Anywhere Environment Variables
# Auto-generated by agent - do not edit manually
# Last updated: ${new Date().toISOString()}
${envLines.join('\n')}
`;

  try {
    // Write to file using sudo (agent runs as kobozo with NOPASSWD sudoers)
    // Use heredoc to avoid command injection
    await execAsync(`sudo bash -c 'cat > /etc/profile.d/vibe-anywhere-env.sh << '\\''ENVEOF'\\''
${envContent}
ENVEOF
chmod 644 /etc/profile.d/vibe-anywhere-env.sh'`);

    console.log(`Updated /etc/profile.d/vibe-anywhere-env.sh with ${Object.keys(envVars).length} variables`);
  } catch (error) {
    console.error('Failed to update /etc/profile.d/vibe-anywhere-env.sh:', error);
    throw new Error(`Failed to write env file: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Update tmux environment using the diff
 * Only changes what's needed (more efficient than full reload)
 */
async function updateTmuxEnvironment(diff: EnvVarDiff): Promise<void> {
  const commands: string[] = [];

  // Unset removed variables
  for (const key of diff.toRemove) {
    commands.push(`tmux set-environment -gu ${key} 2>/dev/null || true`);
  }

  // Set added variables
  for (const [key, value] of Object.entries(diff.toAdd)) {
    const escapedValue = value.replace(/'/g, "'\\''");
    commands.push(`tmux set-environment -g ${key} '${escapedValue}'`);
  }

  // Update changed variables
  for (const [key, { newValue }] of Object.entries(diff.toChange)) {
    const escapedValue = newValue.replace(/'/g, "'\\''");
    commands.push(`tmux set-environment -g ${key} '${escapedValue}'`);
  }

  // Execute all commands if there are any changes
  if (commands.length > 0) {
    try {
      const commandStr = commands.join(' && ');
      await execAsync(commandStr);
      console.log(`Updated tmux environment: ${commands.length} changes applied`);
    } catch (error) {
      // Non-critical error - tmux might not be running or var doesn't exist
      console.warn('Tmux environment update had errors (non-critical):', error);
      // Don't throw - /etc/profile.d/ was updated successfully
    }
  } else {
    console.log('No tmux environment changes needed');
  }
}
