'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRepositoryBranches } from '@/hooks/useRepositoryBranches';
import { useAuth } from '@/hooks/useAuth';
import { NetworkConfigInput, isNetworkConfigValid, type NetworkConfigValue } from '@/components/network/network-config-input';
import type { ProxmoxTemplate } from '@/lib/db/schema';

/**
 * Convert a branch name to a human-readable workspace name
 * e.g., "feature/user-login" -> "User Login"
 */
function humanizeBranchName(branch: string): string {
  // Remove common prefixes
  const prefixes = ['feature/', 'bugfix/', 'hotfix/', 'release/', 'fix/', 'feat/', 'chore/', 'docs/'];
  let name = branch;
  for (const prefix of prefixes) {
    if (name.toLowerCase().startsWith(prefix)) {
      name = name.slice(prefix.length);
      break;
    }
  }

  // Split by separators (-, _, /)
  const words = name.split(/[-_\/]+/).filter(Boolean);

  // Capitalize each word
  return words
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

type WorkspaceDialogTab = 'basic' | 'advanced';

export interface CreateWorkspaceOptions {
  name: string;
  branchName: string;
  baseBranch?: string;
  // Advanced options
  staticIpAddress?: string;
  staticIpGateway?: string;
  forcedVmid?: number;
  overrideTemplateId?: string;
}

interface CreateWorkspaceDialogProps {
  isOpen: boolean;
  repositoryId: string | null;
  initialBranch?: string | null; // Pre-select this branch as "use existing"
  templates?: ProxmoxTemplate[]; // Available templates for override selection
  onClose: () => void;
  onCreate: (options: CreateWorkspaceOptions) => Promise<void>;
  isLoading: boolean;
}

export function CreateWorkspaceDialog({
  isOpen,
  repositoryId,
  initialBranch,
  templates = [],
  onClose,
  onCreate,
  isLoading,
}: CreateWorkspaceDialogProps) {
  // Basic options state
  const [name, setName] = useState('');
  const [branchName, setBranchName] = useState('');
  const [baseBranch, setBaseBranch] = useState('');
  const [branchType, setBranchType] = useState<'new' | 'existing'>('new');
  const [error, setError] = useState<string | null>(null);
  const [initialized, setInitialized] = useState(false);
  // Track if fields were auto-generated (so we can update them on keystroke)
  const [nameWasAutoGenerated, setNameWasAutoGenerated] = useState(true);
  const [branchWasAutoGenerated, setBranchWasAutoGenerated] = useState(true);

  // Tab state
  const [activeTab, setActiveTab] = useState<WorkspaceDialogTab>('basic');

  // Advanced options state
  const [networkConfig, setNetworkConfig] = useState<NetworkConfigValue>({ ipAddress: '', gateway: '' });
  const [forcedVmid, setForcedVmid] = useState('');
  const [vmidError, setVmidError] = useState<string | null>(null);
  const [vmidValidating, setVmidValidating] = useState(false);
  const [overrideTemplateId, setOverrideTemplateId] = useState<string | null>(null);

  const { token } = useAuth();

  // Handle branch updates from WebSocket without closing dropdown
  const handleBranchesUpdated = useCallback((newBranches: string[]) => {
    // Preserve selection if still valid, otherwise select first branch
    setBaseBranch((current) => {
      if (current && newBranches.includes(current)) {
        return current;
      }
      // Try to select default branch or first available
      if (newBranches.includes('main')) return 'main';
      if (newBranches.includes('master')) return 'master';
      return newBranches[0] || '';
    });
  }, []);

  // Use the new hook for fetching branches with WebSocket updates
  const {
    branches,
    isLoading: branchesLoading,
    isRefreshing,
  } = useRepositoryBranches({
    repositoryId: isOpen ? repositoryId : null,
    onBranchesUpdated: handleBranchesUpdated,
  });

  // Initialize state when dialog opens
  useEffect(() => {
    if (isOpen && !initialized) {
      // If initialBranch provided, use "existing" mode with that branch
      if (initialBranch) {
        setBranchType('existing');
        setBaseBranch(initialBranch);
        // Auto-populate workspace name from branch
        const humanName = humanizeBranchName(initialBranch);
        setName(humanName);
        setNameWasAutoGenerated(true);
      } else {
        setBranchType('new');
      }
      setInitialized(true);
    }
    // Reset state when dialog closes
    if (!isOpen) {
      setInitialized(false);
      setName('');
      setBranchName('');
      setBaseBranch('');
      setError(null);
      setNameWasAutoGenerated(true);
      setBranchWasAutoGenerated(true);
      // Reset advanced options
      setActiveTab('basic');
      setNetworkConfig({ ipAddress: '', gateway: '' });
      setForcedVmid('');
      setVmidError(null);
      setOverrideTemplateId(null);
    }
  }, [isOpen, initialBranch, initialized]);

  // Set initial baseBranch when branches first load (only if no initialBranch)
  useEffect(() => {
    if (branches.length > 0 && !baseBranch && !initialBranch) {
      setBaseBranch(branches.includes('main') ? 'main' : branches[0]);
    }
  }, [branches, baseBranch, initialBranch]);

  // Auto-populate workspace name when branch changes in "existing" mode
  useEffect(() => {
    if (branchType === 'existing' && baseBranch && (nameWasAutoGenerated || !name)) {
      const humanName = humanizeBranchName(baseBranch);
      setName(humanName);
      setNameWasAutoGenerated(true);
    }
  }, [baseBranch, branchType, nameWasAutoGenerated, name]);

  // VMID validation on blur
  const handleVmidBlur = async () => {
    if (!forcedVmid) {
      setVmidError(null);
      return;
    }

    const vmid = parseInt(forcedVmid, 10);
    if (isNaN(vmid) || vmid < 100) {
      setVmidError('VMID must be a number >= 100');
      return;
    }

    setVmidValidating(true);
    try {
      const response = await fetch('/api/proxmox/validate-vmid', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ vmid }),
      });
      const data = await response.json();
      if (!data.available) {
        setVmidError(data.message || 'VMID is not available');
      } else {
        setVmidError(null);
      }
    } catch (err) {
      setVmidError('Could not validate VMID');
    } finally {
      setVmidValidating(false);
    }
  };

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Validate advanced options before submit
    if (!isNetworkConfigValid(networkConfig)) {
      setError('Invalid network configuration. Both IP address and gateway are required for static IP.');
      setActiveTab('advanced');
      return;
    }

    if (vmidError) {
      setError('Please fix the VMID error before creating the workspace.');
      setActiveTab('advanced');
      return;
    }

    try {
      const finalBranchName = branchType === 'new' ? branchName : baseBranch;

      // Build options object
      const options: CreateWorkspaceOptions = {
        name,
        branchName: finalBranchName,
        baseBranch: branchType === 'new' ? baseBranch : undefined,
      };

      // Add advanced options if specified
      if (networkConfig.ipAddress && networkConfig.gateway) {
        options.staticIpAddress = networkConfig.ipAddress;
        options.staticIpGateway = networkConfig.gateway;
      }
      if (forcedVmid) {
        options.forcedVmid = parseInt(forcedVmid, 10);
      }
      if (overrideTemplateId) {
        options.overrideTemplateId = overrideTemplateId;
      }

      await onCreate(options);

      // Reset form
      setName('');
      setBranchName('');
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create workspace');
    }
  };

  // Convert workspace name to branch name format
  const workspaceNameToBranch = (workspaceName: string): string => {
    const safeBranchName = workspaceName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, ''); // trim leading/trailing hyphens
    return safeBranchName ? `feature/${safeBranchName}` : '';
  };

  // Handle workspace name changes (bidirectional: also updates branch if auto-generated)
  const handleNameChange = (value: string) => {
    setName(value);
    setNameWasAutoGenerated(false);

    // Auto-generate branch name if it was auto-generated or empty
    if (branchType === 'new' && branchWasAutoGenerated) {
      setBranchName(workspaceNameToBranch(value));
    }
  };

  // Handle branch name changes (bidirectional: also updates workspace name if auto-generated)
  const handleBranchNameChange = (value: string) => {
    setBranchName(value);
    setBranchWasAutoGenerated(false);

    // Auto-generate workspace name if it was auto-generated or empty
    if (branchType === 'new' && nameWasAutoGenerated) {
      setName(humanizeBranchName(value));
    }
  };

  // Check if any advanced options are set
  const hasAdvancedOptions = networkConfig.ipAddress || networkConfig.gateway || forcedVmid || overrideTemplateId;

  // Get ready templates for override selection
  const readyTemplates = templates.filter(t => t.status === 'ready');

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-background-secondary rounded-lg w-full max-w-lg mx-4 max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-border flex items-center justify-between">
          <h2 className="text-lg font-semibold text-foreground">Create Workspace</h2>
          <button
            onClick={onClose}
            className="text-foreground-secondary hover:text-foreground"
          >
            ×
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-border px-4">
          <button
            type="button"
            onClick={() => setActiveTab('basic')}
            className={`px-4 py-2 text-sm font-medium transition-colors
              ${activeTab === 'basic'
                ? 'text-primary border-b-2 border-primary -mb-[1px]'
                : 'text-foreground-secondary hover:text-foreground'}`}
          >
            Basic
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('advanced')}
            className={`px-4 py-2 text-sm font-medium transition-colors flex items-center gap-1.5
              ${activeTab === 'advanced'
                ? 'text-primary border-b-2 border-primary -mb-[1px]'
                : 'text-foreground-secondary hover:text-foreground'}`}
          >
            Advanced
            {hasAdvancedOptions && (
              <span className="px-1.5 py-0.5 text-xs bg-primary/20 text-primary rounded">
                Custom
              </span>
            )}
          </button>
        </div>

        {/* Content */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-4 space-y-4">
          {error && (
            <div className="p-3 bg-error/20 border border-error/50 rounded text-error text-sm">
              {error}
            </div>
          )}

          {/* Basic Tab */}
          {activeTab === 'basic' && (
            <>
              <div>
                <label className="block text-sm text-foreground mb-1">
                  Workspace Name <span className="text-error">*</span>
                </label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => handleNameChange(e.target.value)}
                  placeholder="My Feature"
                  required
                  className="w-full px-3 py-2 bg-background-tertiary border border-border-secondary rounded text-foreground placeholder-foreground-tertiary"
                />
              </div>

              <div>
                <label className="block text-sm text-foreground mb-2">Branch</label>
                <div className="flex gap-4 mb-3">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      checked={branchType === 'new'}
                      onChange={() => setBranchType('new')}
                      className="text-primary"
                    />
                    <span className="text-sm text-foreground">Create new branch</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      checked={branchType === 'existing'}
                      onChange={() => setBranchType('existing')}
                      className="text-primary"
                    />
                    <span className="text-sm text-foreground">Use existing branch</span>
                  </label>
                </div>

                {branchType === 'new' ? (
                  <>
                    <input
                      type="text"
                      value={branchName}
                      onChange={(e) => handleBranchNameChange(e.target.value)}
                      placeholder="feature/my-feature"
                      required
                      className="w-full px-3 py-2 bg-background-tertiary border border-border-secondary rounded text-foreground placeholder-foreground-tertiary mb-3"
                    />
                    <div className="flex items-center gap-2 mb-1">
                      <label className="text-sm text-foreground-secondary">Base Branch</label>
                      {isRefreshing && (
                        <span className="text-xs text-foreground-tertiary animate-pulse">
                          Refreshing...
                        </span>
                      )}
                    </div>
                    <select
                      value={baseBranch}
                      onChange={(e) => setBaseBranch(e.target.value)}
                      disabled={branchesLoading}
                      className="w-full px-3 py-2 bg-background-tertiary border border-border-secondary rounded text-foreground disabled:opacity-50"
                    >
                      {branchesLoading && branches.length === 0 ? (
                        <option value="">Loading branches...</option>
                      ) : branches.length === 0 ? (
                        <option value="">No branches available</option>
                      ) : (
                        branches.map((branch) => (
                          <option key={branch} value={branch}>
                            {branch}
                          </option>
                        ))
                      )}
                    </select>
                  </>
                ) : (
                  <>
                    <div className="flex items-center gap-2 mb-1">
                      <label className="text-sm text-foreground-secondary sr-only">Select Branch</label>
                      {isRefreshing && (
                        <span className="text-xs text-foreground-tertiary animate-pulse">
                          Refreshing...
                        </span>
                      )}
                    </div>
                    <select
                      value={baseBranch}
                      onChange={(e) => setBaseBranch(e.target.value)}
                      disabled={branchesLoading}
                      className="w-full px-3 py-2 bg-background-tertiary border border-border-secondary rounded text-foreground disabled:opacity-50"
                    >
                      {branchesLoading && branches.length === 0 ? (
                        <option value="">Loading branches...</option>
                      ) : branches.length === 0 ? (
                        <option value="">No branches available</option>
                      ) : (
                        branches.map((branch) => (
                          <option key={branch} value={branch}>
                            {branch}
                          </option>
                        ))
                      )}
                    </select>
                  </>
                )}
              </div>
            </>
          )}

          {/* Advanced Tab */}
          {activeTab === 'advanced' && (
            <div className="space-y-6">
              <p className="text-sm text-foreground-secondary">
                Override container creation settings. Leave empty to use defaults.
              </p>

              {/* Static IP Configuration */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-2">
                  Static IP Configuration
                </label>
                <NetworkConfigInput
                  value={networkConfig}
                  onChange={setNetworkConfig}
                  disabled={isLoading}
                />
              </div>

              {/* Force VMID */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Force VMID
                </label>
                <input
                  type="number"
                  value={forcedVmid}
                  onChange={(e) => {
                    setForcedVmid(e.target.value);
                    setVmidError(null); // Clear error on change
                  }}
                  onBlur={handleVmidBlur}
                  placeholder="Auto-allocate"
                  min={100}
                  disabled={isLoading}
                  className={`w-full px-3 py-2 bg-background-tertiary border rounded text-foreground placeholder-foreground-tertiary transition-colors
                    ${vmidError ? 'border-error' : 'border-border-secondary'}
                    ${isLoading ? 'opacity-50 cursor-not-allowed' : 'focus:outline-none focus:border-primary'}`}
                />
                {vmidValidating && (
                  <p className="text-xs text-foreground-tertiary mt-1 animate-pulse">
                    Validating VMID...
                  </p>
                )}
                {vmidError && (
                  <p className="text-xs text-error mt-1">{vmidError}</p>
                )}
                <p className="text-xs text-foreground-tertiary mt-1">
                  Specify exact Proxmox VMID. Must be &gt;= 100.
                </p>
              </div>

              {/* Override Template */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Override Template
                </label>
                <select
                  value={overrideTemplateId || ''}
                  onChange={(e) => setOverrideTemplateId(e.target.value || null)}
                  disabled={isLoading}
                  className="w-full px-3 py-2 bg-background-tertiary border border-border-secondary rounded text-foreground disabled:opacity-50"
                >
                  <option value="">Use repository default</option>
                  {readyTemplates.map((template) => (
                    <option key={template.id} value={template.id}>
                      {template.name}
                      {template.vmid && ` (VMID: ${template.vmid})`}
                    </option>
                  ))}
                </select>
                <p className="text-xs text-foreground-tertiary mt-1">
                  Select a different template than the repository default
                </p>
                {readyTemplates.length === 0 && (
                  <p className="text-xs text-warning mt-1">
                    No ready templates available. Create and provision a template first.
                  </p>
                )}
              </div>
            </div>
          )}
        </form>

        {/* Footer */}
        <div className="p-4 border-t border-border flex justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-foreground-secondary hover:text-foreground transition-colors"
            disabled={isLoading}
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={isLoading || !name || (branchType === 'new' ? !branchName : !baseBranch) || !!vmidError || vmidValidating}
            className="px-4 py-2 bg-primary hover:bg-primary-hover disabled:bg-background-input disabled:opacity-50 disabled:cursor-not-allowed rounded text-foreground transition-colors"
          >
            {isLoading ? 'Creating...' : 'Create Workspace'}
          </button>
        </div>
      </div>
    </div>
  );
}
